import type { Metadata } from "next";
import { Roboto, Rajdhani } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: false,
});

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rajdhani",
  preload: false,
});

export const metadata: Metadata = {
  title: "Super Bikezz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rajdhani.variable}>
        <main className="max-w-7xl mx-auto border">{children}</main>
      </body>
    </html>
  );
}
